handle_customer_query:
  description: >
    A customer has reached out with the following query: '{customer_query}'.
    1. Understand the customer's needs.
    2. If necessary, use the 'Knowledge Base Query Tool' to search for past similar issues, solutions, relevant information, or established guidelines.
       When using the tool, formulate a concise search query based on the customer's problem or the information you need.
    3. Based on your understanding and any information retrieved, formulate a helpful, empathetic, and Markdown-formatted response.
    4. If you find relevant past conversations or guidelines, you can mention general learnings or approaches but do not directly quote full logs unless specifically asked and relevant.
  expected_output: >
    A clear, concise, and helpful response to the customer's query, **formatted in Markdown**.
    The response should be ready to be saved directly into a .md file.
    If information was found using the Knowledge Base Query Tool, briefly mention how past learnings helped,
    e.g., "Based on similar situations, I'd suggest..." or "I found some helpful guidelines regarding your issue."
  output_file: 'output/{generated_filename}.md' # <<< Make sure this line uses '{generated_filename}'
  # agent will be assigned in crew.py